config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'our_school', to: 'pages#our_school'
  get 'fbla', to: 'pages#fbla'
  get 'about_us', to: 'pages#about_us'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_of_service', to: 'pages#terms_of_service'

  get 'donate', to: 'donations#donate'
  get 'donate/preview', to: 'donations#preview_donation'
  get 'donate/success', to: 'donations#donation_success'
  post '/donate/process_payment', to: 'donations#charge_donation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor

  enum frequency: %i(one_time monthly yearly)

  def currency_symbol
    Money.new(self.price_in_cents, self.currency.to_sym).currency.symbol
  end

end

app/models/donor.rb
class Donor < ApplicationRecord
  has_many :donations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def donate
    @page_title = 'Make a Donation'
    @page_description = "Donating to our organization will empower us to do more
    in our mission to secure the future's of Haitian students. Our operations are
    split between Haiti and USA. We import food and technology from USA into Haiti
    to keep our school at the forefront of innovation. After 2010's disastrous
    earthquake, we have rebuilt! However, we still need the funds to return and
    surpass our former glory."
  end

  def preview_donation
    @page_title = 'Submit Your Donation'

    donation_type = donation_params[:donation_type]
    price_in_cents = donation_params[:"#{donation_type}_price"].to_i * 100
    currency = donation_params[:"#{donation_type}_currency"]

    @donation = Donation.new(
      price_in_cents: price_in_cents,
      frequency: donation_type,
      currency: currency
    )
  end

  def charge_donation
    @donor = Donor.new(donor_attrs)
    @donation = Donation.new(donation_params)

    begin
      exp_month, exp_year = payment_params[:expiry].split('/').map(&:to_i)
      exp_year = "20#{exp_year}".to_i
      @token = Stripe::Token.create({
        card: {
          number: payment_params[:number],
          exp_month: exp_month,
          exp_year: exp_year,
          cvc: payment_params[:cvc],
        }
      })

      @customer = Stripe::Customer.create({
        email: @donor.email,
        source: @token.id
      })
      @donor.customer_id = @customer.id

      @charge = Stripe::Charge.create({
        amount: @donation.price_in_cents,
        currency: @donation.currency,
        customer: @customer.id,
        description: 'FOHAMU Donation',
      })

      if @charge.paid
        if @donor.save!
          @donation.donor_id = @donor.id
          @donation.last_payment_date = DateTime.now

          render json: { success: true } if @donation.save!
        end
      end
    rescue Stripe::CardError => e
      render json: { error: e.message }
    end
  end

  def donation_success
    @page_title = 'Thank You'
  end

  def cancel_donation
  end



  private

  def donation_params
    params.require(:donation).permit(
      :donation_type, :monthly_price, :one_time_price, :yearly_price,
      :one_time_currency, :monthly_currency, :yearly_currency,
      :frequency, :currency, :price_in_cents
    )
  end

  def payment_params
    params.require(:payment).permit(:name, :number, :expiry, :cvc)
  end

  def donor_params
    params.require(:donor).permit(
      :address1, :address2, :city, :state, :zip, :phone_number, :email
    )
  end

  def set_address
    line_one = donor_params[:address1]
    line_two = donor_params[:address2]

    return [line_one, line_two].join(', ') unless line_two.empty?

    line_one
  end

  def donor_attrs
    donor_attrs = donor_params.except(:address1, :address2).to_h
    donor_attrs[:address] = set_address
    donor_attrs[:full_name] = payment_params[:name]
    donor_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page_title = 'Home'
    @page_description = "Focus Haitian Music Inc. (FOHAMU) is a charitable,
    tax-exempt, 501(c)(3) organization dedicated to the growth and empowerment of
    Haitian youth and creating a brighter future for Haiti's tomorrow."
  end

  def our_school
    @page_title = "Institution Chrétienne d'Haïti"
    @page_description = "ICDH is a K12 school located in Carrefour, Haiti. Since
    2000, we've provided Haitian youth in an education far beyond the standards of
    the common Haitian educatino. At ICDH, we prepare our students to excel on an
    international scale."
  end

  def fbla
    @page_title = 'FBLA Haiti Chapter'
    @page_description = "FBLA Chapter Haiti has been the soel respresentative of
    Haiti within FBLA-PBL since 2011. Thorugh competing against international
    students, netowrking at the events, and experiencing international travel,
    our program prepares students for a collegiate education abroad. "
  end

  def about_us
    @page_title = 'About Us'
    @page_description = "Focus Haitian Music Inc. (FOHAMU) is a charitable,
    tax-exempt, 501(c)(3) organization. Since 1999, we have worked to give
    Haitian youth a stellar education and initiate them as well-informed,
    global citizens."
  end

  def terms_of_service
    @page_title = 'Terms of Service'
  end

  def privacy_policy
    @page_title = 'Privacy Policy'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end
end

app/views/donations/donate.html.erb
<%= render partial: 'layouts/navbar' %>

<section class="select-donation">
  <div class="overlay"></div>

  <div class=donation-panel>
    <h1>Donate</h1>

    <%= form_tag(donate_preview_path, method: :GET) do %>
      <div class="options">
        <div class="option one-time">
          <div class="header">
            <h2>One-Time</h2>

            <div class="icon">
              <%= image_tag "relieved_face.gif", alt: 'Thanks for your one-time donation. We appreciate your help with empowering our Haitain youth!' %>
            </div>
          </div>
          <%= radio_button_tag 'donation[donation_type]', 'one_time' %>

          <div class="form hidden">
            <div class="amount">
              <%= number_field_tag 'donation[one_time_price]', 10, min: 10 %>
              <%= currency_select('donation', 'one_time_currency', ['USD', 'EUR', 'CAD']) %>
            </div>
          </div>
        </div>

        <div class="option yearly">
          <div class="header">
            <h2>Yearly</h2>

            <div class="icon">
              <%= image_tag "grinning_face_with_smiling_eyes.gif" %>
            </div>
          </div>
          <%= radio_button_tag 'donation[donation_type]', 'yearly' %>

          <div class="form hidden">
            <div class="amount">
              <%= number_field_tag 'donation[yearly_price]', 40, min: 40 %>
              <%= currency_select('donation', 'yearly_currency', ['USD', 'EUR', 'CAD']) %>
            </div>
          </div>
        </div>

        <div class="option monthly">
          <div class="header">
            <h2>Monthly</h2>

            <div class="icon">
              <%= image_tag "beaming_face_with_smiling_eyes.gif" %>
            </div>
          </div>

          <%= radio_button_tag 'donation[donation_type]', 'monthly' %>
          <div class="form hidden">
            <div class="amount">
              <%= number_field_tag 'donation[monthly_price]', 10, min: 10 %>
              <%= currency_select('donation', 'monthly_currency', ['USD', 'EUR', 'CAD']) %>
            </div>
          </div>
        </div>

      </div>

      <div id="submit-donation-type">
        <%= submit_tag "Next", class: 'donate button pwa-element pwa-borders-borderBottom-reveal' %>
      </div>
    <% end %>
  </div>
</section>

app/views/donations/donation_success.html.erb
<%= render partial: 'layouts/navbar' %>

<section class="donation-success">
  <div class="overlay"></div>

  <div class=thanks-panel>
    <h1>Thank You!</h1>

    <p>
      Your contribution will enable us to continue to work towards a brighter
      future for Haiti!
    </p>
  </div>
</section>

app/views/donations/preview_donation.html.erb
<%= render partial: 'layouts/navbar' %>

<section class="payment">
  <div class="payment-panel">
    <h1>Donation</h1>

    <div>
      <h3><%= @donation.frequency.capitalize.gsub('_', '-') %> Amount</h3>
      <p class="price">
        <%= @donation.currency_symbol %><%= @donation.price_in_cents / 100 %>
        <%= @donation.currency %>
      </p>
    </div>

    <div class="payment-info">

      <div class="card-information">
        <div class="card-wrapper">
        </div>

        <form id="card-form">
          <p class="message">Name on Card</p>
          <input type="text" name="name"/>
          <p class="message">Card Number</p>
          <input type="text" name="number" maxlength="19">

          <div class="inline">
            <p class="message">Expiration</p>
            <input type="text" name="expiry"/>
            <p class="message">CVC</p>
            <input type="text" name="cvc"/>
          </div>
        </form>
      </div>

      <div class="donor-info">
        <h3>Address</h3>
        <form id="billing-info"">
          <p class="message">Address 1</p>
          <input type="text" name="address1"/>

          <p class="message">Address 2 (Optional)</p>
          <input type="text" name="address2"/>

          <p class="message">City</p>
          <input type="text" name="city">

          <p class="message">State</p>
          <%= select_tag :state, options_for_select(us_states) %>

          <p class="message">Zip Code</p>
          <input type="text" name="zip">

        </form>

        <h3>Contact Information</h3>
        <form id="contact-info"">
          <p class="message">Phone</p>
          <input type="text" name="phone_number"/>

          <p class="message">Email</p>
          <input type="text" name="email"/>
        </form>
      </div>
    </div>


    <div class="submit">
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      <%= submit_tag "Submit", class: 'donate button pwa-element pwa-borders-borderBottom-reveal' %>
    </div>
  </div>

  <div class="loading">
    <div class="circle-loader">
      <div class="checkmark draw"></div>
    </div>
  </div>
  
</section>

app/views/layouts/_footer.html.erb
<footer>
  <div class=container>
    <div class="company-info">
      <div class="logo">
        <%= image_tag 'logo.png' %>
      </div>

      <div class="info">
        <h3>Focus Haitian Music Inc.</h3>
        <p>
          14736 225th street<br>
          Springfield Gardens, NY 11413
        </p>
      </div>

    </div>

    <div class="social">
      <div class="social-buttons">
        <a href="https://www.facebook.com/focushaiti" class="social-buttons__button social-button social-button--facebook" aria-label="Facebook">
          <span class="social-button__inner">
           <i class="fab fa-facebook-f"></i>
          </span>
        </a>
      </div>
    </div>
  </div>

  <div class="bottom-bar">
    <div class="bar">
      Copyright ©2021 •
      All rights reserved •
      <%= link_to 'Privacy Policy', privacy_policy_path %> •
      <%= link_to 'Terms of Service', terms_of_service_path %>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>

  <div class="desktop">
    <div class="links">
      <%= link_to "Our School", our_school_path %>
      <%= link_to "FBLA", fbla_path %>
      <%= link_to "About Us", about_us_path %>
    </div>

    <div class="donate">
      <%= link_to "Donate", donate_path, class: 'donate button pwa-element pwa-borders-borderBottom-reveal' %>
    </div>
  </div>

  <div class="mobile">
    <div class="pwa-hamburgerMenu4">
      <input type="checkbox" class="pwa-hamburgerCheckbox4">
      <div class="pwa-hamburger4">
        <div class="pwa-hamburgerLayer4"></div>
        <div class="pwa-hamburgerLayer4"></div>
        <div class="pwa-hamburgerLayer4"></div>
      </div>
    </div>

    <div class="menu">
      <ul>
        <li>
          <%= link_to "Our School", our_school_path %>
        </li>
        <li>
          <%= link_to "FBLA", fbla_path %>
        </li>
        <li>
          <%= link_to "About Us", about_us_path %>
        </li>

        <li>
          <div class="donate">
            <%= link_to "Donate", donate_path, class: 'donate button pwa-element pwa-borders-borderBottom-reveal' %>
          </div>
        </li>
      </ul>
    </div>
  </div>

</div>
<div class="slant"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= "#{@page_title}" || 'Focus Haitian Music' %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name=”viewport” content=”width=device-width, initial-scale=1″>
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="theme-color" content="#ffffff">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="<%= @page_description %>">


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>">
    <%= yield %>

    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/pages/about_us.html.erb
<%= render partial: 'layouts/navbar' %>

<section class="hero">
  <div class="overlay">
  </div>
</section>

<section class="mission">
  <h1>Our Mission</h1>

  <p>
    <b>Focus Haitian Music Inc. FOHAMU</b> is a charitable, tax-exempt, 501(c)(3) organization,
    is dedicated to promoting empowerment of people through education, protection of the
    environment, and respect for cultural diversity.<br><br>

   Our institution provides affordable, educational, and outdoor recreational
   activities in a safe, clean, and inviting environment for people of all ages
   through sound business and management practices.  We are committed to achieving
   long lasting change that transforms people's lives and brightens Haiti's future.<br><br>
  </p>

  <h1>Our Work</h1>

  <p>
     Through our programs, we develop individuals with strong leadership qualities and
     innovative mindsets. We are working to reduce poverty and injustice in disadvantaged
     areas and promote democratic values, social change and free expression.<br><br>

     We believe that social change and progress depend on the ability of well-educated
     individuals to transfer their culture heritage and knowledge to future generations.<br><br>

     In this regard, <b>FOHAMU</b> is committed to providing the educational and cultural
     support necessary for the formation of the next generation if Haitian leadership,
     whom will become globally competitive and cognizant of the world conjuncture.<br><br>

     We support construction of schools, water purification and viable community
     events in the United States and abroad.
  </p>
</section>


<section class="founders">
  <div class="founder herbert">

    <div class="header">
      <div class="photo">
        <%= image_tag "herbert_joseph.jpg", class: "founder-img" %>
      </div>
    </div>


    <div class="education">
      <div class="name">
        <h2>Herbert Joseph</h2>
      </div>


      <div class="logo">
        <%= image_tag 'ccny.png' %>
      </div>

      <div class="degree">
        <h3 class="school-name">The City College of New York</h3>
        <h3>
          <b>Master's</b> Degree in <b>Business Administration and Management</b>
        </h3>
      </div>
    </div>

    <div class="description">
      <p>
        After 15 years as an educator at high schools within NYC's public education
        system, Herbert turns his attention back to his origins: Haiti. Choosing
        to teach within NYC's  economically challenged areas, he found personal fulfillment
        when he noticed positive change in the students.<br><br>


        In the United States, poor students have free access books, tech and science labs,
        free breakfast and lunches, free transportation cards, free uniforms (if it is mandated),
        well-trained teachers and administrators, etc. Yet, they have to be coerced
        to attend school.<br><br>

        He noticed that in Haiti, most youngsters are dreaming of such services,
        they have strong dreams and do want to succeed. Students are marching or
        begging for teachers and labs and cafeterias. Give them them the tools,
        and they will amaze the world!

        Since 2000, he has worked to his life's work operating as CEO at
        <b>Focus Haitian Music (FOHAMU)</b>, alongside his brother,
        Jean Joseph.
      </p>
    </div>
  </div>
  <div class="founder jean">

    <div class="header">
      <div class="photo">
        <%= image_tag "jean_2.jpg", class: "founder-img" %>
      </div>
    </div>


    <div class="education">
      <div class="name">
        <h2>Jean Joseph</h2>
      </div>


      <div class="logo">
        <%= image_tag 'ccny.png' %>
      </div>

      <div class="degree">
        <h3 class="school-name">The City College of New York</h3>
        <h3>
          <b>Master's</b> Degree in <b>Education Technology</b>
        </h3>
      </div>


    </div>

    <div class="description">
      <p>
        Since 2000, Jean has been both the Principal and Educator at
        <b>Institution Chrétienne d'Haïti (ICDH)</b>. He oversaw the construction
        and formation of the 5-story educational complex in Carrefour, Haiti.
        Even after the disastrous 2010 earthquake, which left the building destroyed
        and incurred personal losses and injury, his dedication to educating and providing
        support to the Haitian community has only grown stronger.<br><br>


        Jean has rebuilt the school in 2011, and continues to oversee the growth & development
        of not only the students, but of the school staff and adults in the local community.
        He sets the standard of education above and beyond Haitian standards, to give students
        the opportunity to excel internationally.<br><br>

        As Vice Present of FBLA Chapter Haiti, he personally prepares his students to
        excel in the competitive events held in America. He ensures that the students
        are equipped with state-of-the-art technology needed in their classes and gives
        his staff all the tools and techniques necessary to effectively educate. All
        while ensuring a safe and secure environment for everyone involved.
      </p>
    </div>
  </div>

</section>


<section class="contact-us">
  <form id="contact" action="" method="post">
    <h3>Contact Us</h3>

    <fieldset>
      <input placeholder="Your name" type="text" tabindex="1" required autofocus>
    </fieldset>

    <fieldset>
      <input placeholder="Your Email Address" type="email" tabindex="2" required>
    </fieldset>

    <fieldset>
      <input placeholder="Your Phone Number" type="tel" tabindex="3" required>
    </fieldset>

    <fieldset>
      <textarea placeholder="Type your Message Here...." tabindex="5" required></textarea>
    </fieldset>

    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
  </form>
</section>

app/views/pages/home.html.erb
<%= render partial: 'layouts/navbar' %>
<section class="hero">
  <div class="overlay"></div>
  <div class="gradient"></div>
</section>

<section class="our-mission">
  <h1> Empowering Haiti's Youth </h1>

  <div class="values">
    <div class="value globalization">
      <div class="title"> Globalization</div>

      <div class="icon">
        <i class="fas fa-globe-americas"></i>
      </div>

      <div class="description">
        <p>
          We prepare our students with all the tools necessary to excel in
          the global community.<br><br>

          The trend toward the global economic village is clear, and the 21st
          century may very well become known as the century of the “global world”. <br><br>

          As a result, we provide stringent language training focusing on fluency and
          complete comprehension at writing and speaking English. All of our students
          have historically excelled at passing the TOEFL exam.<br><br>

          Not only through language, we have our students adopt a global mindset.
          They remain informed on the happenings in countries abroad and are educated on
          many foreign cultures.
        </p>
      </div>
    </div>

    <div class="value business-savvy">
      <div class="title"> Business-Savvy</div>

      <div class="icon">
        <i class="fas fa-briefcase"></i>
      </div>

      <div class="description">
        <p>
          As of 2019, Haiti's GDP is $14.33 billion and ranked 149th in the world.<br><br>

          Putting political, economic, health, and disaster-related reasons aside; we must do better.<br><br>

          That is why we prepare our students for the world economy and foster a
          strong sense of entrepreneurship.<br><br>

          Our students are exposed to cutting edge technologies and educated at the
          art of capital investments. By practicing paper trading, analyzing tech
          industry & startup trends, and learning practical business administration, we equip our
          students with the tools to be both the founders of tomorrow and thrive in a corporate environment.
        </p>
      </div>
    </div>

    <div class="value leadership">
      <div class="title"> Leadership</div>

      <div class="icon">
        <%= inline_svg_tag('podium.svg') %>
      </div>

      <div class="description">
        <p>
          Leaders do not fall from trees, whole societies must prioritize their
          formation and Haiti is in a desperate need of new innovative, inspiring,
          creative and modern leaders!<br><br>

          We cultivate this trait in our students, so that they may become a greater
          next-generation of Haitian leadership.<br><br>

          We have participated in Future Business Leaders of America for 10 years running,
          as well ass the National Leadership Conference. Our students become skilled
          orators, effective communicators, and adept at planning & organization.
        </p>
      </div>
    </div>
  </div>
</section>

<section class="our-work">
  <div class="header">
    <h1>Our Work</h1>
  </div>

  <div class="grid-container">
    <div class="grid">

      <div class="grid--item grid1">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid2">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid3">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid4">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid5">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid6">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>

      <div class="grid--item grid7">
        <div class="img"></div>

        <div class="container">
        </div>
      </div>
    </div>
  </div>

  <div class="breakdown">
    <div class="panel fbla-work">
      <div class="panel-title">
        <h1>FBLA Chapter Haiti</h1>
      </div>

      <div class="content">
        <div class="logo">
          <%= image_tag 'FBLA-logo.png' %>
        </div>

        <div class="description">
          <p>
            <b>Future Business Leaders of America-Phi Beta Lambda, Inc. (FBLA-PBL)</b>
            is the largest career student business organization in the world.
            Each year, FBLA-PBL helps over 230,000 members prepare for careers
            in business.<br><br>

            For the past 10 years, we have been the sole school representing the
            country of Haiti. All necessary US visas, hotel
            reservations, and airfare are secured on the behalf our participants.<br><br>

            This is far beyond a simple trip abroad or tourism, the impact on our
            students leaves a lasting mark on their work ethics, career outlooks,
            and ambitions.<br><br>

            Our students participate in competitive business-related events and come
            away with a stronger sense of the skills necessary to succeed in modern
            business.<br><br>

            In 20 years of educating in the NYC public schools, instituting
            FBLA in many high schools, I've seen first-hand the impact of
            the program on building cross-cultural experience, networking,
            internships, volunteering, student performance, self-reliance,
            passion projects and collegiate preparation.<br><br>
          </p>
        </div>
      </div>
    </div>

    <div class="panel icdh">
      <div class="panel-title">
        <h1>ICDH</h1>
      </div>

      <div class="content">
        <div class="logo">
          <%= image_tag 'icdh-logo.png' %>
        </div>

        <div class="description">
          <p>
            <b>Institution Chrétienne d'Haïti</b> is a K-12 school located in Carrefour
            since 2000. Our curriculum offers musical arts, science and math. Our
            languages courses span from Haitian Creole, French, English, Spanish,
            and Mandarin Chinese.<br><br>

            In 2011, our school boasted a 100% percentage of success
            in Haitian state examinations at all levels. That level of excellence
            persists, as we wish to excel on an international scale.<br><br>

            Our school acts as a pillar in our community and commonly participates
            in scholastic events with neighboring schools and colleges.<br><br>

            Beyond K-12, our continuing education programs for learning languages
            and professional development are highly lauded. While we often train
            our own staff, the program is freely available to professionals from
            other schools. Raising the bar for education in Haiti is our goal,
            to that end we share our knowledge and expertise to all educators we can.<br><br>

            The American public schools are supported by local, state,
            federal governments and businesses. In Haiti, our establishment is
            supported solely by our non-profit organization.
          </p>
        </div>
      </div>

    </div>
  </div>

</section>